### ISSUE TITLE
SyntaxError: Unexpected token e in JSON at position 0

### ISSUE THREAD

**Issue by ktreharrison** [iann0036/vscode-aws-cloudshell#9]
When trying to use the AWS CloudShell extension, I keep getting  the following error: `SyntaxError: Unexpected token e in JSON at position 0`

I have a role with  `"sts:AssumeRole"` attached, so  I am not sure what is causing the error

**Comment by iann0036** [comment]
Hey @ktreharrison,

Thanks for raising! It looks like the protocol for CloudShell has changed significantly since I wrote this extension. I'll try to find some time to look into it however it's not going to be a simple task, so don't hold out on this working any time soon I'm sorry to say.

**Comment by ktreharrison** [comment]
Thanks for the update ! — I will try to config an ssh setup in the meantime
